// Mapping photos de chantier RT Toiture 74 → articles blog
export const BLOG_IMAGES = {
  "quand-nettoyer-toiture-montagne":      { src: "/images/chantier-chalet.jpg",          alt: "Chantier démoussage toiture chalet savoyard Haute-Savoie — RT Toiture 74" },
  "mousses-toit-dangereuses":             { src: "/images/avant-demossage-mousses.jpg",   alt: "Mousses et lichens sur tuiles béton avant traitement — RT Toiture 74" },
  "demoussage-manuelle-vs-haute-pression":{ src: "/images/avant-demossage-lichens.jpg",   alt: "Lichens blancs sur toiture avant démoussage professionnel Haute-Savoie" },
  "traitement-anti-mousse-professionnel": { src: "/images/apres-demossage-net.jpg",       alt: "Toiture après traitement anti-mousse professionnel — résultat net RT Toiture 74" },
  "traitement-hydrofuge-indispensable":   { src: "/images/apres-demossage-net.jpg",       alt: "Tuiles propres après démoussage et hydrofuge — RT Toiture 74 Haute-Savoie" },
  "detecter-fuite-toiture":               { src: "/images/avant-mousse-grise.jpg",        alt: "Tuiles béton encrassées avec mousses — signe d'entretien urgent Haute-Savoie" },
  "entretien-toiture-montagne-guide":     { src: "/images/chantier-chalet.jpg",           alt: "Entretien toiture chalet de montagne en Haute-Savoie — RT Toiture 74" },
  "preparer-toiture-hiver-montagne":      { src: "/images/chantier-chalet.jpg",           alt: "Préparation toiture avant hiver en montagne Haute-Savoie — RT Toiture 74" },
  "signes-renover-toiture":               { src: "/images/avant-mousse-grise.jpg",        alt: "Toiture dégradée avec mousses épaisses — signes de rénovation nécessaire" },
  "infiltration-eau-toit-urgence":        { src: "/images/avant-demossage-mousses.jpg",   alt: "Tuiles encrassées source d'infiltration — urgence toiture Haute-Savoie" },
  "prix-refaire-toiture-haute-savoie":    { src: "/images/maison-apres-face.jpg",         alt: "Maison après réfection toiture complète en Haute-Savoie — RT Toiture 74" },
  "cout-demoussage-toiture-2025":         { src: "/images/artisan-toit.jpg",              alt: "Artisan couvreur RT Toiture 74 au travail sur toiture en Haute-Savoie" },
  "gouttieres-bouchees-solution":         { src: "/images/chantier-chalet.jpg",           alt: "Chantier entretien gouttières et toiture chalet Haute-Savoie — RT Toiture 74" },
  "urgence-toiture-tempete":              { src: "/images/avant-demossage-lichens.jpg",   alt: "Toiture endommagée nécessitant intervention urgente en Haute-Savoie" },
  "toiture-resistante-neige":             { src: "/images/chantier-chalet.jpg",           alt: "Toiture de montagne résistante à la neige en Haute-Savoie — RT Toiture 74" },
  "reparation-faitage-prix-methode":      { src: "/images/avant-demossage-lichens.jpg",   alt: "Faîtage toiture en Haute-Savoie à réparer — RT Toiture 74" },
  "couverture-ardoise-prix-avantages":    { src: "/images/chantier-chalet.jpg",           alt: "Chantier couverture ardoise chalet savoyard — RT Toiture 74 Haute-Savoie" },
  "aides-isolation-toiture-haute-savoie": { src: "/images/maison-apres-face.jpg",         alt: "Maison rénovée avec isolation toiture financée MaPrimeRénov' Haute-Savoie" },
  "choisir-couvreur-haute-savoie":        { src: "/images/artisan-toit.jpg",              alt: "Couvreur professionnel certifié RGE en Haute-Savoie — RT Toiture 74" },
  "zinguerie-tout-savoir":                { src: "/images/chantier-chalet.jpg",           alt: "Zinguerie toiture chalet Haute-Savoie gouttières zinc — RT Toiture 74" },
  "cheneau-vs-gouttiere-difference":      { src: "/images/chantier-chalet.jpg",           alt: "Gouttières et chéneau zinc sur chalet Haute-Savoie — RT Toiture 74" },
  "nettoyer-gouttieres-zinc":             { src: "/images/chantier-chalet.jpg",           alt: "Nettoyage gouttières zinc sur toiture de montagne — RT Toiture 74" },
  "toiture-grele-protection":             { src: "/images/avant-demossage-lichens.jpg",   alt: "Toiture tuiles Haute-Savoie après intempéries — RT Toiture 74" },
  "condensation-sous-toiture":            { src: "/images/avant-mousse-grise.jpg",        alt: "Tuiles béton dégradées par humidité et condensation en Haute-Savoie" },
  "isolation-exterieur-toiture-sarking":  { src: "/images/maison-apres-face.jpg",         alt: "Maison après isolation sarking et réfection toiture Haute-Savoie — RT Toiture 74" },
  "ventilation-toiture-essentiel":        { src: "/images/chantier-chalet.jpg",           alt: "Ventilation sous-toiture chalet de montagne en Haute-Savoie — RT Toiture 74" },
  "meilleurs-materiaux-couverture-montagne": { src: "/images/chantier-chalet.jpg",        alt: "Matériaux de couverture pour toiture de montagne Haute-Savoie — RT Toiture 74" },
  "toiture-bac-acier-montagne":           { src: "/images/chantier-chalet.jpg",           alt: "Toiture bac acier sur bâtiment de montagne en Haute-Savoie — RT Toiture 74" },
  "toiture-lauze-tradition-savoyarde":    { src: "/images/chantier-chalet.jpg",           alt: "Toiture traditionnelle savoyarde chalet Haute-Savoie — RT Toiture 74" },
  "subventions-maprimenrenov-toiture":    { src: "/images/maison-apres-face.jpg",         alt: "Rénovation toiture financée par MaPrimeRénov' en Haute-Savoie — RT Toiture 74" },
  "erreurs-renovation-toiture":           { src: "/images/avant-demossage-mousses.jpg",   alt: "Toiture mal entretenue avec mousses — erreurs à éviter Haute-Savoie" },
  "reperer-probleme-etancheite":          { src: "/images/avant-mousse-grise.jpg",        alt: "Problème d'étanchéité toiture — mousse et dégradation tuiles Haute-Savoie" },
  "peinture-toiture-produit-choisir":     { src: "/images/apres-peinture-marron.jpg",     alt: "Résultat peinture toiture marron sur tuiles Haute-Savoie — RT Toiture 74" },
  "duree-vie-toiture-tuiles":             { src: "/images/avant-mousse-grise.jpg",        alt: "Tuiles béton en fin de vie avec mousses — durée de vie dépassée Haute-Savoie" },
  "toiture-assurance-couverture":         { src: "/images/avant-demossage-lichens.jpg",   alt: "Toiture avec lichens à déclarer à l'assurance — Haute-Savoie RT Toiture 74" },
  "toiture-permis-construire-haute-savoie": { src: "/images/maison-apres-face.jpg",       alt: "Réfection toiture avec déclaration préalable en Haute-Savoie — RT Toiture 74" },
  "panneaux-solaires-toiture-haute-savoie": { src: "/images/chantier-chalet.jpg",         alt: "Toiture chalet Haute-Savoie compatible panneaux solaires — RT Toiture 74" },
  "revetement-hydrofuge-teinte":          { src: "/images/apres-peinture-marron.jpg",     alt: "Toiture après revêtement hydrofuge teinté — résultat RT Toiture 74 Haute-Savoie" },
  "renovation-energetique-commencer":     { src: "/images/maison-apres-face.jpg",         alt: "Maison rénovée énergétiquement en Haute-Savoie — RT Toiture 74" },
  "amiante-toiture-que-faire":            { src: "/images/avant-mousse-grise.jpg",        alt: "Ancienne toiture en fibrociment à diagnostiquer en Haute-Savoie — RT Toiture 74" },
  "certification-rge-importance":         { src: "/images/artisan-toit.jpg",              alt: "Artisan couvreur RGE Qualibat Haute-Savoie — RT Toiture 74" },
  "couleur-toiture-haute-savoie":         { src: "/images/apres-peinture-marron.jpg",     alt: "Choix couleur toiture peinte en Haute-Savoie — RT Toiture 74" },
};
