import React from "react";

const EXPERTISE_CONTENT = {
  "demoussage-nettoyage-toiture": {
    title: "Démoussage en Haute-Savoie : une nécessité climatique, pas un luxe",
    paragraphs: [
      "En Haute-Savoie, les toitures subissent des conditions que peu d'autres régions connaissent. Entre les hivers rigoureux du Chablais, les chutes de neige abondantes des stations comme Megève ou Chamonix, et les printemps pluvieux qui saturent les versants nord d'humidité, vos tuiles et ardoises font face à une pression climatique permanente. C'est précisément dans ces conditions que mousses, lichens et algues prolifèrent avec une rapidité déconcertante.",
      "Une mousse apparemment anodine n'est jamais sans conséquence. Elle retient l'humidité contre les matériaux de couverture, accélère les cycles de gel et de dégel qui fissurent les tuiles, et finit par soulever les faîtières et les bavettes. Sur un chalet exposé au nord à 1 200 mètres d'altitude, une toiture non entretenue peut perdre 30 à 40 % de sa résistance structurelle en moins de dix ans. À Annecy, dans le bassin lémanique ou dans les vallées de l'Arve, l'humidité stagnante et les brouillards hivernaux créent les mêmes conditions, parfois plus insidieuses car moins visibles.",
      "Notre équipe intervient sur tout le département 74, de Vétraz-Monthoux à Sallanches, de Douvaine à La Roche-sur-Foron. Nous connaissons intimement les spécificités de chaque microclimat : l'exposition des versants, les vents dominants qui chargent en humidité, les zones d'ombre prolongée qui favorisent la croissance des végétaux. Cette connaissance du terrain, acquise au fil des années de chantiers en Haute-Savoie, nous permet d'adapter précisément notre intervention à votre toiture.",
      "Le nettoyage haute pression que nous pratiquons n'est pas une simple aspersion d'eau. La pression est minutieusement calibrée selon le type de matériau — plus douce pour les ardoises friables, plus soutenue pour les tuiles béton encrassées — afin d'éliminer sans abîmer. Nous complétons systématiquement le nettoyage par une inspection visuelle complète : tuiles fêlées ou manquantes, joints de faîtage dégradés, problèmes de noue ou de solins. Un chantier de démoussage devient ainsi l'occasion d'un diagnostic complet de l'état de votre couverture, sans surcoût.",
      "Entretenir régulièrement sa toiture en Haute-Savoie, c'est réaliser un investissement rentable. Un démoussage tous les 3 à 5 ans coûte infiniment moins cher qu'une réfection partielle ou totale due à des dégradations accélérées par la négligence. Couvreur certifié RGE dans le département 74, Reinhart Timothée vous accompagne avec transparence, depuis le devis gratuit jusqu'à la réception du chantier, avec une garantie sur nos prestations et un suivi dans la durée.",
    ],
  },
  "traitement-fongicide-toiture": {
    title: "Traitement fongicide en montagne : protéger durablement contre un ennemi invisible",
    paragraphs: [
      "Après le nettoyage, la vraie bataille commence. Car les spores responsables des mousses et des champignons sont microscopiques, omniprésentes dans l'air des vallées alpines, et capables de recoloniser une toiture non traitée en moins de deux saisons. En Haute-Savoie, l'alternance d'humidité et de chaleur estivale, couplée aux brouillards persistants de l'automne et aux dégels printaniers, crée un environnement parfaitement adapté à leur développement.",
      "Le traitement fongicide professionnel que nous appliquons ne se contente pas de tuer les organismes présents en surface. Il pénètre dans la porosité des tuiles et ardoises pour former une barrière biocide durable, empêchant toute recolonisation pendant trois à cinq ans selon l'altitude et l'exposition. Sur les versants nord — particulièrement fréquents en Haute-Savoie avec son relief complexe — où l'ombre entretient une humidité permanente, nous adaptons la concentration et la méthode d'application pour garantir une efficacité maximale.",
      "Nos produits fongicides sont sélectionnés parmi les formulations professionnelles homologuées, conformes à la directive biocide européenne. Ils sont biodégradables et sans danger pour les jardins, les potagers et la faune environnante — un point crucial dans les zones rurales et périurbaines de la Haute-Savoie où coexistent habitat et nature. L'application se fait par pulvérisation homogène, assurant une couverture uniforme même sur les reliefs complexes de vos toitures alpines.",
      "Au-delà de la protection contre les mousses, le traitement fongicide ralentit considérablement l'altération superficielle des matériaux. Les cycles de gel et de dégel si fréquents entre 600 et 1 500 mètres d'altitude fragilisent progressivement les tuiles non protégées. Un fongicide bien appliqué réduit l'absorption d'eau en surface, limitant mécaniquement les dommages causés par les gels hivernaux. C'est pourquoi nous le recommandons systématiquement après chaque nettoyage de toiture, notamment dans les zones de montagne exposées comme Cluses, Bonneville, Megève ou les villages des Aravis.",
      "En tant que couvreur local en Haute-Savoie depuis de nombreuses années, nous avons traité des centaines de toitures dans le département 74. Nous connaissons la différence entre les toitures de Sciez exposées aux brouillards du Léman et celles de Chamonix battues par les vents alpins. Cette expertise locale — pas apprise dans un manuel mais gagnée chantier après chantier — fait la différence entre un traitement qui tient deux ans et un qui en tient cinq.",
    ],
  },
  "traitement-hydrofuge-toiture": {
    title: "Hydrofuge toiture en Haute-Savoie : la protection garantie 10 ans contre le gel et les infiltrations",
    paragraphs: [
      "Dans les Alpes et le Préalpes savoyardes, l'eau est omniprésente. Elle tombe sous forme de pluie fine en automne dans le Chablais, s'accumule en neige lourde en hiver sur les chalets de montagne, et s'infiltre sournoisement lors des dégels de printemps dans les matériaux poreux de couverture. C'est précisément cette réalité climatique qui fait du traitement hydrofuge non pas une option, mais une nécessité pour tout propriétaire soucieux de la longévité de sa toiture en Haute-Savoie.",
      "Le phénomène de gel-dégel est le premier ennemi des toitures alpines. Lorsque l'eau s'infiltre dans les micropores des tuiles ou des ardoises, elle se transforme en glace au premier gel, augmentant de volume et faisant éclater le matériau de l'intérieur. Sur une maison à 900 mètres d'altitude, avec 80 à 120 cycles de gel par hiver, une tuile non protégée peut se fissurer puis se fragmenter en quelques saisons. L'hydrofuge crée une barrière moléculaire invisible qui repousse l'eau à la surface du matériau sans jamais le laisser s'imbiber — l'eau perle et s'écoule, le matériau reste sec.",
      "Notre traitement hydrofuge professionnel, garanti 10 ans, utilise des formulations siloxane de dernière génération. Contrairement aux produits grand public, ces siloxanes micro-moléculaires pénètrent en profondeur dans le matériau avant de polymériser, formant une protection invisible de l'intérieur plutôt qu'un simple film de surface qui s'écaille. Le résultat est visible immédiatement à l'effet perlant que vous observez après la première pluie : l'eau roule en billes sur vos tuiles, entraînant salissures et dépôts sans jamais s'infiltrer.",
      "Nous intervenons pour le traitement hydrofuge sur tout le bassin annécien, le Pays de Gex frontalier, la vallée de l'Arve, le Chablais et toutes les zones préalpines du département 74. Chaque intervention commence par un nettoyage préalable obligatoire — l'hydrofuge ne s'applique efficacement que sur un support parfaitement propre et sec. Nous garantissons une préparation rigoureuse du support et un délai de séchage adapté aux conditions météorologiques locales avant application.",
      "Investir dans un traitement hydrofuge professionnel à 20-45€/m², c'est éviter une réfection complète à 150-250€/m² dans dix ans. Sur une toiture de 150 m², la différence représente des dizaines de milliers d'euros. En tant qu'artisan couvreur RGE basé en Haute-Savoie, nous vous accompagnons pour ce choix stratégique avec des devis clairs, transparents et sans engagement. Votre toiture mérite la même attention que les autres éléments structurels de votre maison alpine.",
    ],
  },
  "revetement-hydrofuge-teinte": {
    title: "Revêtement hydrofuge teinté en Haute-Savoie : quand la protection rencontre l'esthétique alpine",
    paragraphs: [
      "Le patrimoine architectural de Haute-Savoie est remarquable. Des chalets traditionnels aux tuiles rouge brique des villages chablaisiens, des ardoises sombres des chalets d'altitude aux toitures contemporaines des lotissements annéciens, chaque toiture raconte une histoire et contribue à l'identité visuelle du territoire. Lorsque les années et les intempéries alpines finissent par blanchir, ternir ou tacher ces couvertures, le revêtement hydrofuge teinté s'impose comme la solution la plus intelligente : en une seule intervention, vous restaurez à la fois l'esthétique et l'imperméabilité de votre toiture.",
      "Contrairement à la peinture opaque qui masque les matériaux sous une couche filmogène, le revêtement hydrofuge teinté imprègne le support en profondeur tout en déposant des pigments dans les pores du matériau. Le résultat est beaucoup plus naturel, beaucoup moins susceptible d'écaillage, et permet à la toiture de « respirer » — condition indispensable dans les zones humides de montagne où la condensation doit pouvoir s'évacuer. Sur une tuile terre cuite délavée de Vétraz-Monthoux ou d'Annemasse, l'effet est spectaculaire : la couleur d'origine retrouvée, sans plastique apparent.",
      "En Haute-Savoie, les contraintes réglementaires des Plans Locaux d'Urbanisme imposent souvent des teintes spécifiques pour les toitures, afin de préserver l'harmonie visuelle des villages et stations. Nous maîtrisons ces exigences communales et vous guidons dans le choix de la teinte la plus appropriée à votre bâtiment, à votre environnement et aux règles locales. Notre palette comprend l'ensemble des teintes traditionnelles alpines — rouge Bourgogne, ardoise bleutée, brun terre de Sienne, ocre savoyard — ainsi que des teintes contemporaines pour les constructions récentes.",
      "L'application du revêtement hydrofuge teinté nécessite une expertise technique précise. La surface doit être parfaitement propre, sèche, et la température doit se situer entre 8°C et 25°C — ce qui, en Haute-Savoie, limite les interventions aux périodes de printemps et d'automne clémentes. Nous appliquons systématiquement deux couches : une couche de primaire teinté qui pénètre et colore en profondeur, puis une couche de finition hydrofuge qui scelle la surface et garantit la durabilité de la teinte face aux UV et aux intempéries alpines.",
      "Le résultat d'un revêtement hydrofuge teinté professionnel est immédiatement valorisant. Lors d'une vente immobilière, une toiture visuellement impeccable peut faire la différence sur la perception globale du bien. Les estimateurs immobiliers de la région anécienne et chablaisienne le confirment : une toiture rénovée récemment est un argument de vente concret, surtout dans un marché immobilier alpin où l'entretien général du bâti est scruté à la loupe par les acquéreurs.",
    ],
  },
  "peinture-toiture": {
    title: "Peinture de toiture en Haute-Savoie : transformation complète pour les couvertures en fin de cycle",
    paragraphs: [
      "Certaines toitures arrivent à un stade où l'hydrofuge teinté ne suffit plus. Les couleurs sont totalement passées, les matériaux présentent des hétérogénéités visuelles importantes, ou le projet est un changement radical de teinte pour moderniser l'aspect d'une maison. Dans ces cas, la peinture de toiture professionnelle est la réponse adaptée : une transformation visuelle complète, opaque et durable, qui redonne à votre couverture l'apparence du neuf.",
      "En Haute-Savoie, les peintures pour toiture doivent satisfaire des exigences bien supérieures aux standards des régions de plaine. Le rayonnement UV est nettement plus intense en altitude — on l'estime à 10 % plus élevé par tranche de 1 000 mètres — ce qui accélère considérablement la dégradation des liants et des pigments. Les peintures que nous utilisons sont spécifiquement formulées pour résister à ce rayonnement accru, aux variations thermiques extrêmes entre les nuits d'hiver en dessous de -15°C et les journées d'été dépassant 40°C en surface de toiture.",
      "La préparation du support conditionne intégralement la durée de vie d'une peinture de toiture. Nous ne transigeons jamais sur cette étape : nettoyage haute pression complet, démoussage, traitement fongicide, ponçage des zones friables ou décollées, application d'un primaire d'accrochage adapté au support. Sur une toiture en tuiles béton vieillissantes — très répandues dans les lotissements des années 1980-1990 de la région d'Annecy, Bonneville ou Cluses — la préparation représente parfois autant de travail que la peinture elle-même, mais c'est elle qui garantit la tenue.",
      "Nous intervenons pour la peinture de toiture sur tout le département 74, des bords du Léman aux premières neiges des Aravis. Chaque chantier commence par une visite diagnostic gratuite où nous évaluons l'état du support, discutons du résultat souhaité et sélectionnons ensemble la teinte et le produit les plus adaptés. Notre connaissance des PLU locaux nous permet de vous orienter vers les teintes autorisées dans votre commune, évitant toute déconvenue administrative après les travaux.",
      "Une peinture de toiture professionnelle bien réalisée dure entre 8 et 12 ans. Pour une toiture de 150 m², l'investissement représente quelques milliers d'euros contre des dizaines de milliers pour une réfection complète. C'est une solution de réhabilitation intermédiaire parfaitement cohérente pour les toitures dont la structure est encore saine mais dont l'aspect esthétique est détérioré. Nos travaux sont garantis, notre assurance décennale couvre l'ensemble de nos interventions, et notre réputation locale en Haute-Savoie repose sur des centaines de clients satisfaits depuis de nombreuses années.",
    ],
  },
  "couverture-toiture": {
    title: "Couverture de toiture en Haute-Savoie : l'expertise alpine d'un artisan certifié RGE",
    paragraphs: [
      "La toiture est l'enveloppe protectrice de votre maison. En Haute-Savoie, cette protection prend une dimension cruciale que les propriétaires de plaine ne peuvent pas vraiment appréhender. Une toiture alpine doit encaisser des charges de neige pouvant dépasser 200 kg/m² en période de fort enneigement, résister aux vents de fœhn qui peuvent atteindre 100 km/h dans les vallées, supporter des écarts de température de 50°C entre les nuits de janvier et les journées de juillet, et évacuer des précipitations parmi les plus importantes de France. Concevoir et réaliser une telle couverture requiert une expertise technique spécifique que seul un artisan couvreur formé et expérimenté en conditions alpines peut offrir.",
      "Nous maîtrisons tous les types de couverture traditionnels et contemporains de la région. Les tuiles béton adaptées au gel, les ardoises naturelles si prisées dans les communes patrimoniales du Pays de Gex et du Genevois, les lauzes traditionnelles des villages savoyards, les toitures bac acier des constructions récentes d'altitude — chaque matériau a ses spécificités de pose, ses règles d'art et ses exigences d'entretien. Le choix du bon matériau dépend de l'altitude, de l'orientation, de la pente du toit, des contraintes du PLU et du style architectural du bâtiment.",
      "Notre certification RGE (Reconnu Garant de l'Environnement) n'est pas une simple étiquette commerciale. Elle atteste d'une formation continue, du respect des règles de l'art et de la maîtrise des normes thermiques en vigueur. En pratique, cela signifie que les travaux de couverture que nous réalisons peuvent ouvrir droit aux aides de l'État — MaPrimeRénov', éco-PTZ, TVA à taux réduit — lorsqu'ils sont combinés à des travaux d'isolation de combles. Nous vous accompagnons dans la constitution de votre dossier de financement pour maximiser les aides auxquelles vous avez droit.",
      "En cas d'urgence — tuiles arrachées par une tempête, fuite active après une chute de neige exceptionnelle, dégât causé par la chute d'un arbre — nous assurons une intervention d'urgence 7 jours sur 7 sur tout le département 74. La première étape est toujours la sécurisation : bâchage professionnel ancré pour résister au vent, étanchéification provisoire des zones atteintes, sécurisation des accès. Ensuite seulement nous établissons un diagnostic précis et proposons la réparation durable adaptée.",
      "De Vétraz-Monthoux à Chamonix, de Sciez à La Roche-sur-Foron, notre zone d'intervention couvre l'ensemble du département. Chaque devis est gratuit, détaillé et établi après visite sur site — jamais à distance sur photos. C'est la seule façon d'évaluer précisément l'état de la charpente, l'accessibilité du chantier, les spécificités du bâtiment et de vous proposer une solution techniquement et financièrement juste. La confiance se construit dès le premier contact.",
    ],
  },
  "etancheite-toit-terrasse-epdm": {
    title: "Étanchéité EPDM Retridex en Haute-Savoie : la solution définitive pour vos toits terrasses alpins",
    paragraphs: [
      "Le toit terrasse représente un défi particulier en région alpine. Contrairement aux toitures en pente qui évacuent naturellement les eaux et la neige, le toit plat accumule l'eau et doit supporter le poids de la neige sans pouvoir s'en décharger. En Haute-Savoie, cette problématique est amplifiée par des hivers où l'enneigement peut être considérable : certains hivers, des toits terrasses à Megève ou Chamonix supportent des charges de 200 à 300 kg/m² de neige tassée. Dans ces conditions, une étanchéité défaillante ou vieillissante est une bombe à retardement.",
      "Le système EPDM Retridex que nous utilisons est aujourd'hui la référence mondiale pour l'étanchéité des toits plats et terrasses. L'EPDM — Éthylène Propylène Diène Monomère — est un caoutchouc synthétique développé initialement pour l'industrie aérospatiale, qui présente des propriétés exceptionnelles : allongement à la rupture supérieur à 300 %, résistance aux UV sans dégradation sur des décennies, tenue entre -45°C et +120°C, imperméabilité totale même sous une pression de colonne d'eau. En termes simples : rien de ce que le climat alpin peut lui imposer ne peut l'abîmer.",
      "La durabilité de l'EPDM Retridex dépasse 50 ans avec un entretien minimal — contre 15 à 20 ans pour les membranes bitumineuses traditionnelles. Sur un immeuble ou une villa en Haute-Savoie, l'investissement dans une étanchéité EPDM est donc rentabilisé bien avant la première refonte nécessaire pour un toit bitumé. Et contrairement à la pose à la flamme du bitume, l'EPDM Retridex se pose entièrement à froid, sans risque d'incendie et sans émanations nocives — un avantage considérable en milieu habité.",
      "Notre méthode de pose garantit une étanchéité parfaite jusque dans les points les plus délicats : relevés de membrane sur les acrotères, habillage des souches de ventilation, solin d'évacuation des eaux pluviales, gestion des angles rentrants et sortants. Ces points singuliers sont statistiquement la source de 90 % des infiltrations sur toit terrasse. Notre maîtrise technique de ces détails de pose — acquise sur des centaines de chantiers en Haute-Savoie — est ce qui différencie une étanchéité qui tient cinquante ans d'une réparation qui en tient cinq.",
      "Nous intervenons pour l'étanchéité EPDM Retridex sur des toits terrasses de toutes superficies : petites terrasses de maisons individuelles dans le bassin annécien, grandes terrasses d'immeubles résidentiels à Annemasse ou Cluses, toits terrasses d'équipements collectifs, extensions de maison contemporaines dans les villages du Chablais. Chaque intervention commence par une visite technique gratuite où nous évaluons l'état du support existant, définissons le calepinage de pose et établissons un devis précis. La transparence est notre marque de fabrique.",
    ],
  },
  "zinguerie": {
    title: "Zinguerie en Haute-Savoie : l'artisanat du zinc face aux défis du climat alpin",
    paragraphs: [
      "La zinguerie est souvent négligée jusqu'au jour où une gouttière débordante inonde une façade, où un abergement de cheminée défaillant laisse l'eau s'infiltrer dans la charpente, ou où une descente d'eaux pluviales arrachée par la neige cause des dégâts importants. En Haute-Savoie, les risques liés à une zinguerie dégradée sont amplifiés par les conditions climatiques : les volumes d'eau à évacuer lors des orages de montagne ou des fontes de neige printanières dépassent largement ce que connaissent les régions de plaine, et le gel hivernal sollicite extrêmement les joints et les soudures des éléments de zinguerie.",
      "Le choix du matériau est fondamental en région alpine. Nous recommandons systématiquement le zinc naturel pour son rapport performance-durabilité inégalé : 30 à 50 ans de durée de vie, résistance excellente au gel et à la corrosion, aspect esthétique qui grise élégamment avec le temps pour s'harmoniser avec les façades savoyardes. Pour les projets haut de gamme — chalets de prestige en station, demeures patrimoniales — le cuivre offre une durabilité encore supérieure, dépassant 100 ans, et un cachet incomparable qui prend de la valeur en vieillissant. L'aluminium laqué, plus économique, convient bien aux constructions contemporaines.",
      "L'abergement de cheminée est statistiquement l'un des points de fuite les plus fréquents sur les toitures alpines. La combinaison de dilatation thermique importante, de travail mécanique lié aux variations de poids de neige sur la toiture, et d'exposition directe aux intempéries fragilise rapidement les raccords entre la cheminée et la couverture. Un abergement réalisé par un artisan zingueur qualifié — avec des bavettes latérales correctement engravées dans les joints de maçonnerie, une noue arrière en zinc plié et une bavette avant avec contre-abergement — est la seule solution vraiment durable. Nous réalisons ces ouvrages selon les règles de l'art DTU 40.41 pour une étanchéité garantie sur le long terme.",
      "Les chéneaux encastrés sous les tuiles, particulièrement répandus sur les chalets savoyards traditionnels, sont une autre source fréquente de problèmes. Mal dimensionnés ou obstrués par des feuilles et des mousses, ils débordent en cas de pluie intense ou de fonte de neige rapide, inondant directement la façade et les fondations. Nous nettoyons, réparons et si nécessaire remplaçons ces chéneaux avec des matériaux et des sections adaptés aux débits réels que votre toiture doit évacuer en conditions extrêmes.",
      "De Yvoire à Bonneville, de Talloires à Reignier-Ésery, nous assurons l'entretien et le remplacement complet des installations de zinguerie sur tout le département 74. Nos devis sont gratuits, détaillés et établis après visite sur site. Nous intervenons avec notre propre matériel d'élévation et de sécurisation pour garantir la qualité du travail et la sécurité de nos équipes, sans jamais sous-traiter. La zinguerie que vous payez est réalisée par nos propres mains — c'est notre engagement d'artisan.",
    ],
  },
};

export default function ExpertiseBlock({ slug, serviceName }) {
  const content = EXPERTISE_CONTENT[slug];
  if (!content) return null;

  return (
    <section className="py-16 lg:py-20 bg-white">
      <div className="max-w-4xl mx-auto px-6">
        <div className="mb-8">
          <span className="inline-block text-xs font-semibold uppercase tracking-widest px-3 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 mb-4">
            Expertise locale
          </span>
          <h2 className="font-heading text-2xl md:text-3xl font-bold text-foreground leading-snug">
            {content.title}
          </h2>
        </div>
        <div className="space-y-5">
          {content.paragraphs.map((para, i) => (
            <p key={i} className="text-muted-foreground leading-relaxed text-base">
              {para}
            </p>
          ))}
        </div>
      </div>
    </section>
  );
}